web:
  image: daocloud.io/noahziheng/skyevent-php:latest
  privileged: false
  restart: always
  links:
  - db
  ports:
  - 80:80
  volumes:
  - /home/noah/Documents/SkyEvent:/home
  environment:
  - APP_ENV=dev
phpmyadmin:
  image: phpmyadmin/phpmyadmin:4.6.2-2
  privileged: false
  restart: always
  links:
  - db
  ports:
  - 8080:80
db:
  image: daocloud.io/noahziheng/skyevent-db:latest
  privileged: false
  restart: always
  expose:
  - 3306
  volumes:
  - /data/mysql/skyevent-test:/var/lib/mysql
