web:
  image: daocloud.io/noahziheng/skyevent-php:latest
  privileged: false
  restart: always
  links:
  - redis
  - db
  expose:
  - '80'
  volumes:
  - /data/skyevent/code:/home
  environment:
  - VIRTUAL_HOST=skyevent.tk,www.skyevent.tk
  - APP_ENV=dev
phpmyadmin:
  image: phpmyadmin/phpmyadmin:4.6.2-2
  privileged: false
  restart: always
  links:
  - db
  expose:
  - '80'
  environment:
  - VIRTUAL_HOST=sql.skyevent.tk
db:
  image: index.docker.io/library/mysql:5
  privileged: false
  restart: always
  ports:
  - 3306:3306
  volumes:
  - /data/skyevent/mysql:/var/lib/mysql
  environment:
  - MYSQL_PASSWORD=12345678
  - MYSQL_ROOT_PASSWORD=12345678
  - MYSQL_USER=skyevent
  - MYSQL_DATABASE=skyevent
sso:
  image: daocloud.io/noahziheng/skyevent-sso:master-a7f3e84
  privileged: false
  restart: always
  links:
  - redis
  expose:
  - '80'
  environment:
  - VIRTUAL_HOST=sso.skyevent.tk
redis:
  image: redis
  privileged: false
  restart: always
  ports:
  - 6379:6379
  environment:
  - REDIS_PASS=**None**
