skyevent:
    build: .
    ports:
        - "5000:80"
    links:
        - db
    volumes:
        - .:/var/www/html

db:
    image: "mysql"
    expose:
        - "3306"
    environment:
        - MYSQL_ROOT_PASSWORD=defaultpass